language: rust
rust:
    - stable
cache: cargo
os:
    - linux
sudo: required
services:
    - xvfb
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
script:
    - cargo test
